### ISSUE TITLE
1.3.1 breaks compatibility with SBT 1.2.8

### ISSUE THREAD

**Issue by nigredo-tori** [albuch/sbt-dependency-check#87]
**Describe the bug**

After updating from 1.3.0 to 1.3.1 I get a `NoSuchMethodError` when running `dependencyCheck`.

**Version of sbt-dependency-check used**

The problem occurs using version 1.3.1 of the the plugin.

**Log file**

https://gist.github.com/nigredo-tori/b09e66fda6d1f040da6d5e796906cfd3

**To Reproduce**

1. Create a build with SBT 1.2.8 and sbt-dependency-check 1.3.1
1. Run `dependencyCheck`.

**Expected behavior**

`dependencyCheck` works as intended.

**Additional context**

It's probably not a good idea to build for the latest  SBT version. These are, in general, backward compatible, but not forward compatible. We don't want to accidentally use an API that was not present in the previous versions (like we did here), so we should revert `crossSbtVersions` to `Vector("0.13.18", "1.2.8")`.

**Comment by albuch** [comment]
Hi @nigredo-tori,
good catch, the scripted plugin that I'm using for tests does not catch this type of incompatibility as you can see in the latest build that succeeds for sbt 1.2.8: https://travis-ci.org/albuch/sbt-dependency-check/builds/593451231
However I don't think that you described the aimed compatibility for sbt correctly. They explicitly aim for forward compatibility for sbt plugins as you can see by the [release of sbt 1.2.1](https://github.com/sbt/sbt/releases/tag/v1.2.1) that fixed such an incompatibility.
I'll double check with the sbt folks what the expected behaviour would be in this case.

In the meantime I would recommend to either use sbt-dependency-check v1.3.0 or upgrade your project to sbt v1.3.x.

**Comment by nigredo-tori** [comment]
> good catch, the scripted plugin that I'm using for tests does not catch this type of incompatibility as you can see in the latest build that succeeds for sbt 1.2.8

The problem here seems to be that you build for, and test on, the same SBT version. So you effectively check that your plugin builds for 1.2.8, and then check *that artifact* against 1.2.8. You won't catch any bincompat issues this way.

A proper way to do this would be to build for whatever version you build your published artifact against, and test against different SBT versions. So instead of `^^ $SBT_VERSION` you should somehow put `sbt.version = $SBT_VERSION` to `project/build.properties` in your `scripted` test projects.

> In the meantime I would recommend to either use sbt-dependency-check v1.3.0 or upgrade your project to sbt v1.3.x.

Yes, that's what I am doing right now.

**Comment by albuch** [comment]
> A proper way to do this would be to build for whatever version you build your published artifact against, and test against different SBT versions. So instead of ^^ $SBT_VERSION you should somehow put sbt.version = $SBT_VERSION to project/build.properties in your scripted test projects.
Yeah you're right, i need to set up a different test for that. Thanks.

**Comment by albuch** [comment]
Just released v1.3.3 that should address the issue
